---
kind: pipeline
type: docker
name: docker-build-push

platform:
  os: linux
  arch: amd64

steps:
    
- name: build-and-push-image
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: deepnox/python-ta-lib
    tags: 
      - ${DRONE_COMMIT}.${DRONE_BUILD_NUMBER}
      - ${DRONE_TAG/v/}
      - latest
    dockerfile: ./Dockerfile 
    context: .

trigger:
  ref:
  - refs/tags/*
