language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t 9fevrier/travis-python-ta-lib .

script:
  - docker run --rm --name python-ta-lib -t 9fevrier/travis-python-ta-lib python3 -c 'import talib'
